/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import img.FundoBg;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Atributos;
import models.Classe;
import models.Personagem;
import models.Raca;

/**
 *
 * @author valdenor
 */
public class EditarPersonagem extends javax.swing.JFrame {
    
    private int id;
    private Personagem personagem;;
    /**
     * Get the value of id
     *
     * @return the value of id
     */
    public int getId() {
        return id;
    }

    /**
     * Set the value of id
     *
     * @param id new value of id
     */
    public void setId(int id) {
        this.id = id;
    }
    
    
    private void setFields() throws ClassNotFoundException{
    
        if(personagem != null)
        {
        jComboBoxRacas.getModel().setSelectedItem(personagem.getRaca());
        jComboBoxClasses.getModel().setSelectedItem(personagem.getClasse().get(0).getNome());
        jTextFieldNome.setText(personagem.getNome());
        jTextFieldTendencia.setText(personagem.getTendencia());
        jTextFieldDivindade.setText(personagem.getDivindade());
        jTextPaneDescricao.setText(personagem.getDescricao());
        jTextFieldAtrFor.setText(String.valueOf(personagem.getAtributos().get(0).getValor()));
        jTextFieldAtrDes.setText(String.valueOf(personagem.getAtributos().get(1).getValor()));
        jTextFieldAtrCon.setText(String.valueOf(personagem.getAtributos().get(2).getValor()));
        jTextFieldAtrInt.setText(String.valueOf(personagem.getAtributos().get(3).getValor()));
        jTextFieldAtrSab.setText(String.valueOf(personagem.getAtributos().get(4).getValor()));
        jTextFieldAtrCar.setText(String.valueOf(personagem.getAtributos().get(5).getValor()));
        jTextFieldNivel.setText(String.valueOf(personagem.getNivel())); 
        }
    
    }

    /**
     * Creates new form EditarPersonagem
     */
    public EditarPersonagem(int id) throws ClassNotFoundException {
        this.id = id;
        personagem = Personagem.findById(id);
                
        initComponents();
        setFields();
    }

    public String[] listarRaca() throws ClassNotFoundException {
        ArrayList<Raca> lista = Raca.listarRaca();
        String[] listaRaca = new String[Raca.contarRacas()];
        int i = 0;
        for (Raca raca : lista) {
            listaRaca[i] = raca.getNome();
            i++;
        }
        return listaRaca;
    }

    public String[] listarClasses() throws ClassNotFoundException {
        ArrayList<Classe> lista = Classe.listarClasse();
        String[] listaClasse = new String[Classe.contarClasses()];
        int i = 0;
        for (Classe classe : lista) {
            listaClasse[i] = classe.getNome();
            i++;
        }
        return listaClasse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        fundo2 = null;
        try{
            fundo2 = new FundoBg(getClass().getResource( "/img/fundoEditar.jpg" ).getFile());
        }catch(Exception e){
            fundo2 = new javax.swing.JPanel();
        }
        ;
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelRaca = new javax.swing.JLabel();
        jComboBoxRacas = new javax.swing.JComboBox<>();
        jLabelClasse = new javax.swing.JLabel();
        jComboBoxClasses = new javax.swing.JComboBox<>();
        jLabelTendencia = new javax.swing.JLabel();
        jTextFieldTendencia = new javax.swing.JTextField();
        jPanelAtr = new javax.swing.JPanel();
        jLabelAtrFor = new javax.swing.JLabel();
        jLabelAtrDes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAtrDes = new javax.swing.JTextField();
        jTextFieldAtrFor = new javax.swing.JTextField();
        jTextFieldAtrCon = new javax.swing.JTextField();
        jTextFieldAtrInt = new javax.swing.JTextField();
        jTextFieldAtrSab = new javax.swing.JTextField();
        jTextFieldAtrCar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldModDes = new javax.swing.JTextField();
        jTextFieldModFor1 = new javax.swing.JTextField();
        jTextFieldModCon = new javax.swing.JTextField();
        jTextFieldModInt = new javax.swing.JTextField();
        jTextFieldModSab = new javax.swing.JTextField();
        jTextFieldModCar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDescricao = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelDivindade = new javax.swing.JLabel();
        jTextFieldDivindade = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jLabelNivel = new javax.swing.JLabel();
        jTextFieldNivel = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelNome.setText("Nome");

        jTextFieldNome.setToolTipText("");
        jTextFieldNome.setMinimumSize(new java.awt.Dimension(80, 20));
        jTextFieldNome.setName(""); // NOI18N
        jTextFieldNome.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabelRaca.setText("Raça");
        jLabelRaca.setToolTipText("");

        try{
            jComboBoxRacas.setModel(new javax.swing.DefaultComboBoxModel<>( listarRaca()));
        }catch(Exception e){}
        jComboBoxRacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRacasActionPerformed(evt);
            }
        });

        jLabelClasse.setText("Classe");

        try{
            jComboBoxClasses.setModel(new javax.swing.DefaultComboBoxModel<>(listarClasses()));
        }catch(Exception e){}

        jLabelTendencia.setText("Tendencia");

        jTextFieldTendencia.setPreferredSize(new java.awt.Dimension(50, 20));

        jPanelAtr.setOpaque(false);

        jLabelAtrFor.setText("Força");
        jLabelAtrFor.setToolTipText("");

        jLabelAtrDes.setText("Destreza");

        jLabel3.setText("Constituição");

        jLabel4.setText("Inteligencia");

        jLabel5.setText("Sabedoria");

        jLabel6.setText("Carisma");

        jTextFieldAtrDes.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrFor.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrCon.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrInt.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrSab.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrCar.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel7.setText("Valor");

        jTextFieldModDes.setEditable(false);

        jTextFieldModFor1.setEditable(false);
        jTextFieldModFor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModFor1ActionPerformed(evt);
            }
        });

        jTextFieldModCon.setEditable(false);

        jTextFieldModInt.setEditable(false);

        jTextFieldModSab.setEditable(false);

        jTextFieldModCar.setEditable(false);

        jLabel8.setText("Modificador");

        javax.swing.GroupLayout jPanelAtrLayout = new javax.swing.GroupLayout(jPanelAtr);
        jPanelAtr.setLayout(jPanelAtrLayout);
        jPanelAtrLayout.setHorizontalGroup(
            jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAtrFor)
                    .addComponent(jLabelAtrDes))
                .addGap(23, 23, 23)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtrLayout.createSequentialGroup()
                        .addComponent(jTextFieldAtrDes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldModDes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAtrLayout.createSequentialGroup()
                        .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAtrFor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldModFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtrLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldAtrCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldModCon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAtrLayout.createSequentialGroup()
                        .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAtrLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAtrInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAtrLayout.createSequentialGroup()
                                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAtrCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAtrSab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldModInt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldModSab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldModCar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAtrLayout.setVerticalGroup(
            jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtrFor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAtrFor)
                    .addComponent(jTextFieldModFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtrDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAtrDes)
                    .addComponent(jTextFieldModDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtrCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldModCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtrInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldModInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtrSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldModSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAtrCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldModCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jTextPaneDescricao);

        jLabel1.setText("Descrição do personagem");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelDivindade.setText("Divindade");

        jTextFieldDivindade.setPreferredSize(new java.awt.Dimension(80, 20));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelNivel.setText("Nivel");

        jTextFieldNivel.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout fundo2Layout = new javax.swing.GroupLayout(fundo2);
        fundo2.setLayout(fundo2Layout);
        fundo2Layout.setHorizontalGroup(
            fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addComponent(jButtonVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonExcluir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo2Layout.createSequentialGroup()
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRaca)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxRacas, 0, 119, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelClasse))
                            .addGroup(fundo2Layout.createSequentialGroup()
                                .addComponent(jPanelAtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(fundo2Layout.createSequentialGroup()
                                    .addComponent(jComboBoxClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelTendencia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelDivindade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldDivindade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelNivel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1)))
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        fundo2Layout.setVerticalGroup(
            fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRaca)
                    .addComponent(jComboBoxRacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClasse)
                    .addComponent(jComboBoxClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTendencia)
                    .addComponent(jTextFieldTendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDivindade)
                    .addComponent(jTextFieldDivindade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNivel)
                    .addComponent(jTextFieldNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelAtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addGroup(fundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxRacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRacasActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Atributos atr[] = new Atributos[6];
        Classe classe = new Classe();

        atr[0] = new Atributos();
        atr[1] = new Atributos();
        atr[2] = new Atributos();
        atr[3] = new Atributos();
        atr[4] = new Atributos();
        atr[5] = new Atributos();

        atr[0].setNome("Forca");
        atr[0].setValor(Integer.valueOf(jTextFieldAtrFor.getText()));
        atr[1].setNome("Destreza");
        atr[1].setValor(Integer.valueOf(jTextFieldAtrDes.getText()));
        atr[2].setNome("Constituicao");
        atr[2].setValor(Integer.valueOf(jTextFieldAtrCon.getText()));
        atr[3].setNome("Inteligencia");
        atr[3].setValor(Integer.valueOf(jTextFieldAtrInt.getText()));
        atr[4].setNome("Sabedoria");
        atr[4].setValor(Integer.valueOf(jTextFieldAtrSab.getText()));
        atr[5].setNome("Carisma");
        atr[5].setValor(Integer.valueOf(jTextFieldAtrCar.getText()));

        classe.setIdClasse((jComboBoxClasses.getSelectedIndex() + 1));

        personagem.setDescricao(jTextPaneDescricao.getText());
        personagem.setNome(jTextFieldNome.getText());
        personagem.setTendencia(jTextFieldTendencia.getText());
        personagem.setRaca(jComboBoxRacas.getSelectedItem().toString());
        personagem.setDivindade(jTextFieldDivindade.getText());
        
        int nivel =Integer.valueOf(jTextFieldNivel.getText());
        try {
            personagem.update();
             classe.update(nivel,personagem.getIdPersonagem());
            for (int i = 0; i < atr.length; i++) {
                atr[i].setIdAtributo(i + 1);
            }
            Atributos.update(atr, personagem.getIdPersonagem());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NovoPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            Personagem.delete(id);
            this.setVisible(false);
            new ListaPersonagens().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditarPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldModFor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModFor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModFor1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fundo2;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxClasses;
    private javax.swing.JComboBox<String> jComboBoxRacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAtrDes;
    private javax.swing.JLabel jLabelAtrFor;
    private javax.swing.JLabel jLabelClasse;
    private javax.swing.JLabel jLabelDivindade;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRaca;
    private javax.swing.JLabel jLabelTendencia;
    private javax.swing.JPanel jPanelAtr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAtrCar;
    private javax.swing.JTextField jTextFieldAtrCon;
    private javax.swing.JTextField jTextFieldAtrDes;
    private javax.swing.JTextField jTextFieldAtrFor;
    private javax.swing.JTextField jTextFieldAtrInt;
    private javax.swing.JTextField jTextFieldAtrSab;
    private javax.swing.JTextField jTextFieldDivindade;
    private javax.swing.JTextField jTextFieldModCar;
    private javax.swing.JTextField jTextFieldModCon;
    private javax.swing.JTextField jTextFieldModDes;
    private javax.swing.JTextField jTextFieldModFor1;
    private javax.swing.JTextField jTextFieldModInt;
    private javax.swing.JTextField jTextFieldModSab;
    private javax.swing.JTextField jTextFieldNivel;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTendencia;
    private javax.swing.JTextPane jTextPaneDescricao;
    // End of variables declaration//GEN-END:variables
}
