/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import img.FundoBg;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.Classe;
import models.Personagem;
import models.Personagem_has_atributos;
import models.Raca;

/**
 *
 * @author valdenor
 */
public class ListaPersonagens extends javax.swing.JFrame {
    
 
    private  void preencherTabela(){
        DefaultTableModel lista = (DefaultTableModel) jTableLista.getModel();
        try {
            ArrayList<Personagem> listaPersonagem = Personagem.listarPersonagem();
             while(lista.getRowCount() >0){
                lista.removeRow(0);
            }
            for(Personagem jogador : listaPersonagem){
            lista.addRow(new Object[]{
                jogador.getIdPersonagem(),
                jogador.getNome(),
                jogador.getRaca(),
                jogador.getClasse().get(0).getNome(),
                jogador.getNivel(),
                jogador.getAtributos().get(0).getValor(),
                jogador.getAtributos().get(1).getValor(),
                jogador.getAtributos().get(2).getValor(),
                jogador.getAtributos().get(3).getValor(),
                jogador.getAtributos().get(4).getValor(),
                jogador.getAtributos().get(5).getValor(),
                
            });
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListaPersonagens.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form ListaPersonagens
     */
    public ListaPersonagens() {
        initComponents();
        preencherTabela();
       
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = null;
        try{
            fundo = new FundoBg(getClass().getResource( "/img/fundoTabela.jpg" ).getFile());
        }catch(Exception e){
            fundo = new javax.swing.JPanel();
        };
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Personagens");
        setResizable(false);

        jTableLista.setFont(new java.awt.Font("Vladimir Script", 0, 30)); // NOI18N
        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nome", "Raça", "Classe", "nivel", "FOR", "DES", "CON", "INT", "SAB", "CAR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLista.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableLista.setOpaque(false);
        jTableLista.setRowHeight(28);
        jTableLista.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecao(evt);
            }
        });
        jScrollPane4.setViewportView(jTableLista);
        if (jTableLista.getColumnModel().getColumnCount() > 0) {
            jTableLista.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableLista.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTableLista.getColumnModel().getColumn(2).setPreferredWidth(140);
            jTableLista.getColumnModel().getColumn(3).setPreferredWidth(120);
        }
        jTableLista.setAutoResizeMode(jTableLista.AUTO_RESIZE_ALL_COLUMNS);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltar))
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);

    }//GEN-LAST:event_jButtonVoltarActionPerformed


    
    
    private void selecao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecao
        
        this.setVisible(false);
        EditarPersonagem personagem = null;
        try {
            int id = (int) jTableLista.getModel().getValueAt(jTableLista.getSelectedRow(), 0);
            System.out.println(id);
            personagem = new EditarPersonagem(id);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListaPersonagens.class.getName()).log(Level.SEVERE, null, ex);
        }
        personagem.setVisible(true);
    }//GEN-LAST:event_selecao



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fundo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableLista;
    // End of variables declaration//GEN-END:variables
}
