/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import img.FundoBg;
import models.Personagem;

/**
 *
 * @author valdenor
 */
public class MenuPrincipal extends javax.swing.JFrame {

    

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try{
            Fundo = new FundoBg(getClass().getResource( "/img/taverna.jpg" ).getFile());
            jButtonCreditos = new javax.swing.JButton();
            jPanelBotoes = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            JButtonListar = new javax.swing.JButton();
            jButtonCreate = new javax.swing.JButton();
            jPanelTitulo = new javax.swing.JPanel();
            jLabelTitulo = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Gerenciador de Personagens");
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            setResizable(false);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        }catch(Exception e){
            Fundo = new javax.swing.JPanel();
        }
        Fundo.setOpaque(false);

        jButtonCreditos.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButtonCreditos.setText("Sobre");

        jPanelBotoes.setOpaque(false);
        jPanelBotoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        String texto = "0";
        try{
            texto = Personagem.contaPersonagem();
        }catch(Exception e){}
        jLabel1.setFont(new java.awt.Font("Blackadder ITC", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText(texto + " fichas cadastradas");
        jPanelBotoes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        JButtonListar.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        JButtonListar.setText("Listar todos os Personagens");
        JButtonListar.setOpaque(false);
        JButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonListarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(JButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 270, 30));

        jButtonCreate.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButtonCreate.setText("Novo Personagem");
        jButtonCreate.setOpaque(false);
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 30));

        jPanelTitulo.setOpaque(false);

        jLabelTitulo.setFont(new java.awt.Font("Blackadder ITC", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Projeto D&D RPG -- Gerenciador de Personagens");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(jLabelTitulo))
        );

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButtonCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonListarActionPerformed

        this.setVisible(false);
        ListaPersonagens p = new ListaPersonagens();
        p.setVisible(true);

    }//GEN-LAST:event_JButtonListarActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed

        this.setVisible(false);
        NovoPersonagem p = new NovoPersonagem();
        p.setVisible(true);
       

    }//GEN-LAST:event_jButtonCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fundo;
    private javax.swing.JButton JButtonListar;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonCreditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables

}
