/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import img.FundoBg;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Atributos;
import models.Classe;
import models.Personagem;
import models.Raca;

/**
 *
 * @author valdenor
 */
public class NovoPersonagem extends javax.swing.JFrame {

    public String[] listarClasses() throws ClassNotFoundException {
        ArrayList<Classe> lista = Classe.listarClasse();
        String[] listaClasse = new String[Classe.contarClasses()];
        int i = 0;
        for (Classe classe : lista) {
            listaClasse[i] = classe.getNome();
            i++;
        }
        return listaClasse;
    }

    public String[] listarRaca() throws ClassNotFoundException {
        ArrayList<Raca> lista = Raca.listarRaca();
        String[] listaRaca = new String[Raca.contarRacas()];
        int i = 0;
        for (Raca raca : lista) {
            listaRaca[i] = raca.getNome();
            i++;
        }
        return listaRaca;
    }

    /**
     * Creates new form NovoPersonagem
     */
    public NovoPersonagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        fundo = null;
        try{
            fundo = new FundoBg(getClass().getResource( "/img/fundoNovo.jpg" ).getFile());
        }catch(Exception e){
            fundo = new javax.swing.JPanel();
        }
        ;
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelRaca = new javax.swing.JLabel();
        jComboBoxRacas = new javax.swing.JComboBox<>();
        jLabelClasse = new javax.swing.JLabel();
        jComboBoxClasses = new javax.swing.JComboBox<>();
        jLabelTendencia = new javax.swing.JLabel();
        jTextFieldTendencia = new javax.swing.JTextField();
        jPanelAtr = new javax.swing.JPanel();
        jLabelAtrFor = new javax.swing.JLabel();
        jLabelAtrDes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAtrDes = new javax.swing.JTextField();
        jTextFieldAtrFor = new javax.swing.JTextField();
        jTextFieldAtrCon = new javax.swing.JTextField();
        jTextFieldAtrInt = new javax.swing.JTextField();
        jTextFieldAtrSab = new javax.swing.JTextField();
        jTextFieldAtrCar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDescricao = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelDivindade = new javax.swing.JLabel();
        jTextFieldDivindade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelNome.setFont(new java.awt.Font("Blackadder ITC", 3, 24)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 204, 204));
        jLabelNome.setLabelFor(jTextFieldNome);
        jLabelNome.setText("Nome");

        jTextFieldNome.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldNome.setToolTipText("");
        jTextFieldNome.setMinimumSize(new java.awt.Dimension(80, 20));
        jTextFieldNome.setName(""); // NOI18N
        jTextFieldNome.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabelRaca.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabelRaca.setForeground(new java.awt.Color(0, 204, 204));
        jLabelRaca.setLabelFor(jComboBoxRacas);
        jLabelRaca.setText("Raça");
        jLabelRaca.setToolTipText("");

        try{
            jComboBoxRacas.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
            jComboBoxRacas.setModel(new javax.swing.DefaultComboBoxModel<>( listarRaca()));
        }catch(Exception e){}
        jComboBoxRacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRacasActionPerformed(evt);
            }
        });

        jLabelClasse.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabelClasse.setForeground(new java.awt.Color(0, 204, 204));
        jLabelClasse.setText("Classe");

        try{
            jComboBoxClasses.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
            jComboBoxClasses.setModel(new javax.swing.DefaultComboBoxModel<>(listarClasses()));
        }catch(Exception e){}

        jLabelTendencia.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabelTendencia.setForeground(new java.awt.Color(0, 204, 204));
        jLabelTendencia.setLabelFor(jTextFieldTendencia);
        jLabelTendencia.setText("Tendencia");

        jTextFieldTendencia.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldTendencia.setPreferredSize(new java.awt.Dimension(50, 20));

        jPanelAtr.setOpaque(false);

        jLabelAtrFor.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabelAtrFor.setForeground(new java.awt.Color(0, 204, 204));
        jLabelAtrFor.setText("Força");
        jLabelAtrFor.setToolTipText("");

        jLabelAtrDes.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabelAtrDes.setForeground(new java.awt.Color(0, 204, 204));
        jLabelAtrDes.setText("Destreza");

        jLabel3.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Constituição");

        jLabel4.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Inteligencia");

        jLabel5.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Sabedoria");

        jLabel6.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Carisma");

        jTextFieldAtrDes.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldAtrDes.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrFor.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldAtrFor.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrCon.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldAtrCon.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrInt.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldAtrInt.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrSab.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldAtrSab.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextFieldAtrCar.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldAtrCar.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanelAtrLayout = new javax.swing.GroupLayout(jPanelAtr);
        jPanelAtr.setLayout(jPanelAtrLayout);
        jPanelAtrLayout.setHorizontalGroup(
            jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldAtrCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAtrFor)
                    .addComponent(jLabelAtrDes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAtrDes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAtrFor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldAtrCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldAtrInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldAtrSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAtrLayout.setVerticalGroup(
            jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAtrFor)
                    .addComponent(jTextFieldAtrFor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAtrDes)
                    .addComponent(jTextFieldAtrDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAtrCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAtrInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAtrSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldAtrCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextPaneDescricao.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jTextPaneDescricao);

        jLabel1.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Descrição do personagem");

        jButtonSalvar.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelDivindade.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        jLabelDivindade.setForeground(new java.awt.Color(0, 204, 204));
        jLabelDivindade.setText("Divindade");

        jTextFieldDivindade.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jTextFieldDivindade.setPreferredSize(new java.awt.Dimension(80, 20));

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRaca))
                    .addComponent(jPanelAtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(fundoLayout.createSequentialGroup()
                                .addComponent(jComboBoxRacas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelClasse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTendencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDivindade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDivindade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRaca)
                    .addComponent(jComboBoxRacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClasse)
                    .addComponent(jComboBoxClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTendencia)
                    .addComponent(jTextFieldTendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDivindade)
                    .addComponent(jTextFieldDivindade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelAtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxRacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRacasActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Personagem personagem = new Personagem();
        Atributos atr[] = new Atributos[6];
        Classe classe = new Classe();
        
        atr[0] = new Atributos();
        atr[1] = new Atributos();
        atr[2] = new Atributos();
        atr[3] = new Atributos();
        atr[4] = new Atributos();
        atr[5] = new Atributos();

        atr[0].setNome("Forca");
        atr[0].setValor(Integer.valueOf(jTextFieldAtrFor.getText()));
        atr[1].setNome("Destreza");
        atr[1].setValor(Integer.valueOf(jTextFieldAtrDes.getText()));
        atr[2].setNome("Constituicao");
        atr[2].setValor(Integer.valueOf(jTextFieldAtrCon.getText()));
        atr[3].setNome("Inteligencia");
        atr[3].setValor(Integer.valueOf(jTextFieldAtrInt.getText()));
        atr[4].setNome("Sabedoria");
        atr[4].setValor(Integer.valueOf(jTextFieldAtrSab.getText()));
        atr[5].setNome("Carisma");
        atr[5].setValor(Integer.valueOf(jTextFieldAtrCar.getText()));

        classe.setIdClasse((jComboBoxClasses.getSelectedIndex() + 1));
        
        personagem.setDescricao(jTextPaneDescricao.getText());
        personagem.setNome(jTextFieldNome.getText());
        personagem.setTendencia(jTextFieldTendencia.getText());
        personagem.setRaca(jComboBoxRacas.getSelectedItem().toString());
        personagem.setDivindade(jTextFieldDivindade.getText());

        try {
            personagem.setIdPersonagem(Personagem.getLastId() + 1);
            personagem.salvar();
            classe.salvar(personagem.getIdPersonagem());
            for (int i = 0; i < atr.length; i++) {
                atr[i].setIdAtributo(i+1);
                atr[i].salvar(personagem.getIdPersonagem());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NovoPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            this.setVisible(false);
            new MenuPrincipal().setVisible(true);
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel fundo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxClasses;
    private javax.swing.JComboBox<String> jComboBoxRacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAtrDes;
    private javax.swing.JLabel jLabelAtrFor;
    private javax.swing.JLabel jLabelClasse;
    private javax.swing.JLabel jLabelDivindade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRaca;
    private javax.swing.JLabel jLabelTendencia;
    private javax.swing.JPanel jPanelAtr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAtrCar;
    private javax.swing.JTextField jTextFieldAtrCon;
    private javax.swing.JTextField jTextFieldAtrDes;
    private javax.swing.JTextField jTextFieldAtrFor;
    private javax.swing.JTextField jTextFieldAtrInt;
    private javax.swing.JTextField jTextFieldAtrSab;
    private javax.swing.JTextField jTextFieldDivindade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTendencia;
    private javax.swing.JTextPane jTextPaneDescricao;
    // End of variables declaration//GEN-END:variables
}
